spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB   # uploaded_file_size default 1MB max 10MB


mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # running log
    map-underscore-to-camel-case: true  # Mapping: phone_number => phoneNumber

  global-config:
    db-config:
      id-type: ASSIGN_ID   # auto_increment
